# Generated by Django 2.2.16 on 2020-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='lastname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
